language: node_js
node_js: node
# don't connect to sauce labs unless running functional tests
# before_install: if [ "${TRAVIS_MODE}" != "funcTests" ]; then unset SAUCE_USERNAME && unset SAUCE_ACCESS_KEY; fi
script: ./scripts/travis.sh
after_script: if [ "${TRAVIS_MODE}" = "funcTests" ]; then echo "Sauce connect log:" && cat /home/travis/sauce-connect.log; fi
env:
  global:
    - SAUCE_USERNAME=mangui
  matrix:
    - TRAVIS_MODE=build
    - TRAVIS_MODE=unitTests
    - TRAVIS_MODE=funcTests UA=chrome              OS="Windows 10"  STREAM=arte
    - TRAVIS_MODE=funcTests UA=MicrosoftEdge       OS="Windows 10"  STREAM=arte
    - TRAVIS_MODE=funcTests UA=firefox             OS="Windows 10"  STREAM=arte
    - TRAVIS_MODE=funcTests UA=safari              OS="OS X 10.11"  STREAM=arte UA_VERSION="9.0"
#    - TRAVIS_MODE=funcTests UA="internet explorer" OS="Windows 8.1" STREAM=arte
    - TRAVIS_MODE=funcTests UA=chrome              OS="Windows 10"  STREAM=bigBuckBunnyABR
    - TRAVIS_MODE=funcTests UA=MicrosoftEdge       OS="Windows 10"  STREAM=bigBuckBunnyABR
    - TRAVIS_MODE=funcTests UA=firefox             OS="Windows 10"  STREAM=bigBuckBunnyABR
    - TRAVIS_MODE=funcTests UA=safari              OS="OS X 10.11"  STREAM=bigBuckBunnyABR UA_VERSION="9.0"
#    - TRAVIS_MODE=funcTests UA="internet explorer" OS="Windows 8.1" STREAM=bigBuckBunnyABR
    - TRAVIS_MODE=funcTests UA=chrome              OS="Windows 10"  STREAM=bigBuckBunny480p
    - TRAVIS_MODE=funcTests UA=MicrosoftEdge       OS="Windows 10"  STREAM=bigBuckBunny480p
    - TRAVIS_MODE=funcTests UA=firefox             OS="Windows 10"  STREAM=bigBuckBunny480p
    - TRAVIS_MODE=funcTests UA=safari              OS="OS X 10.11"  STREAM=bigBuckBunny480p UA_VERSION="9.0"
#    - TRAVIS_MODE=funcTests UA="internet explorer" OS="Windows 8.1" STREAM=bigBuckBunny480p
    - TRAVIS_MODE=funcTests UA=chrome              OS="Windows 10"  STREAM=issue666
    - TRAVIS_MODE=funcTests UA=MicrosoftEdge       OS="Windows 10"  STREAM=issue666
    - TRAVIS_MODE=funcTests UA=firefox             OS="Windows 10"  STREAM=issue666
    - TRAVIS_MODE=funcTests UA=safari              OS="OS X 10.11"  STREAM=issue666 UA_VERSION="9.0"
#    - TRAVIS_MODE=funcTests UA="internet explorer" OS="Windows 8.1" STREAM=issue666
    - TRAVIS_MODE=funcTests UA=chrome              OS="Windows 10"  STREAM=issue649
    - TRAVIS_MODE=funcTests UA=MicrosoftEdge       OS="Windows 10"  STREAM=issue649
    - TRAVIS_MODE=funcTests UA=firefox             OS="Windows 10"  STREAM=issue649
    - TRAVIS_MODE=funcTests UA=safari              OS="OS X 10.11"  STREAM=issue649 UA_VERSION="9.0"
#    - TRAVIS_MODE=funcTests UA="internet explorer" OS="Windows 8.1" STREAM=issue649
#    - TRAVIS_MODE=funcTests UA=chrome              OS="Windows 10"  STREAM=nasa
#    - TRAVIS_MODE=funcTests UA=MicrosoftEdge       OS="Windows 10"  STREAM=nasa
#    - TRAVIS_MODE=funcTests UA=firefox             OS="Windows 10"  STREAM=nasa
#    - TRAVIS_MODE=funcTests UA=safari              OS="OS X 10.11"  STREAM=nasa UA_VERSION="9.0"
#    - TRAVIS_MODE=funcTests UA="internet explorer" OS="Windows 8.1" STREAM=nasa
    - TRAVIS_MODE=funcTests UA=chrome              OS="Windows 10"  STREAM=closedcaptions
    - TRAVIS_MODE=funcTests UA=MicrosoftEdge       OS="Windows 10"  STREAM=closedcaptions
    - TRAVIS_MODE=funcTests UA=firefox             OS="Windows 10"  STREAM=closedcaptions
#    - TRAVIS_MODE=funcTests UA=safari              OS="OS X 10.11"  STREAM=closedcaptions UA_VERSION="9.0"
#    - TRAVIS_MODE=funcTests UA="internet explorer" OS="Windows 8.1" STREAM=closedcaptions
    - TRAVIS_MODE=funcTests UA=chrome              OS="Windows 10"  STREAM=oceans_aes
    - TRAVIS_MODE=funcTests UA=MicrosoftEdge       OS="Windows 10"  STREAM=oceans_aes
    - TRAVIS_MODE=funcTests UA=firefox             OS="Windows 10"  STREAM=oceans_aes
    - TRAVIS_MODE=funcTests UA=safari              OS="OS X 10.11"  STREAM=oceans_aes UA_VERSION="9.0"
    - TRAVIS_MODE=funcTests UA="internet explorer" OS="Windows 8.1" STREAM=oceans_aes
    - TRAVIS_MODE=funcTests UA=chrome              OS="Windows 10"  STREAM=aac
#    - TRAVIS_MODE=funcTests UA=MicrosoftEdge       OS="Windows 10"  STREAM=aac
#    - TRAVIS_MODE=funcTests UA=firefox             OS="Windows 10"  STREAM=aac
#    - TRAVIS_MODE=funcTests UA=safari              OS="OS X 10.11"  STREAM=oceans_aes UA_VERSION="9.0"
    - TRAVIS_MODE=funcTests UA=chrome              OS="Windows 10"  STREAM=mp3
    - TRAVIS_MODE=funcTests UA=firefox             OS="Windows 10"  STREAM=mp3
#    - TRAVIS_MODE=funcTests UA=safari              OS="OS X 10.11"  STREAM=mp3 UA_VERSION="9.0"

addons:
  sauce_connect: true
  jwt:
    secure: TxJT041jqRf4raCwtNJRb0rz2gGvEaADZjWO41UQND2+YIZ//S9qB2C4YyrL1BBsn8/ebdHr0cd18PwCzoBSEmoCdoAWXmqBaaLvM1DOeQkKJbU3+pFmWtv1qGqRXJLEAysNvzhG0sLdvBc0M7a/CWxqRfx1O3lGhLnTlAW33LlQndjJ8vh3SGQm8HxFR1503ujPd7V1jGwduVwaQp4zbAKTnQ4MLugmJf6UKiTc+YILMrVWOwipOIyYHh2GqbChd/v1PXff26XCNJXcaRZKJ8JosWyBpq5t4zlPO0qDfHpqbEuYK44xm4vzbZS94P/KF8BYzdtxQYLrxoS1UlnUYU7RmzqgL3y3AM7nzX/cXvJcoNXfUK2BpsB754XNyQfRmXOdRiHoC8+wwPqGkH/KCrmS4UIOqv4THfmDbrtewfcDTgKOzHxGcT1IsUq9BTxMNtxSwpHTHUXTXrzpS/UBDvrlc+9qPTqf+e6QL1aG+JT5sOg5REm2hMy0j18/Kr+HLXkehxEgJ6JrybyHUkkJrfcuWgVDu7Lv3cxlrtSMXi7TIwSB75NMoM8AE71GEVjXwpOw/0giwnmGsJNNi01ztod0UFe2V2rS+yPI1WNZIJ7Fw66U0oOKJ1rb4Iksl86n5Y2snHsxK8q5jhKaAaiWgGK5kVTAgF89t/GXYyNH6cI=
